# Generated by Django 5.2.17 on 2026-08-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSafetyScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('total_frames_processed', models.PositiveIntegerField()),
                ('overall_risk_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('environment_warning', models.CharField(max_length=255)),
                ('spoof_detected', models.BooleanField(default=False)),
                ('spoof_reasons', models.JSONField(default=list)),
                ('final_perclos', models.FloatField()),
                ('max_blink_duration_ms', models.IntegerField()),
                ('scan_timestamp', models.DateTimeField()),
                ('sudden_braking_detected', models.BooleanField(default=False)),
                ('sudden_braking_events', models.PositiveIntegerField(default=0)),
                ('swerving_detected', models.BooleanField(default=False)),
                ('swerving_events', models.PositiveIntegerField(default=0)),
                ('accelerometer_samples', models.PositiveIntegerField(default=0)),
                ('gyroscope_samples', models.PositiveIntegerField(default=0)),
                ('max_acceleration_magnitude', models.FloatField()),
                ('average_acceleration_magnitude', models.FloatField()),
                ('max_gyroscope_magnitude', models.FloatField()),
                ('accelerometer_data', models.JSONField(default=list)),
                ('gyroscope_data', models.JSONField(default=list)),
            ],
        ),
    ]
