# Generated by Django 5.2.17 on 2026-08-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_driversafetyscan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driversafetyscan',
            options={'ordering': ['-scan_timestamp']},
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='average_acceleration_magnitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='environment_warning',
            field=models.CharField(default='No environment warning', max_length=255),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='final_perclos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='max_acceleration_magnitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='max_blink_duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='max_gyroscope_magnitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='overall_risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='risk_level',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='status',
            field=models.CharField(default='success', max_length=50),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='total_frames_processed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
