# Generated by Django 5.2.17 on 2026-08-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0003_alter_driversafetyscan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driversafetyscan',
            options={},
        ),
        migrations.AddField(
            model_name='driversafetyscan',
            name='truck_id',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='accelerometer_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='environment_warning',
            field=models.CharField(blank=True, default='No environment warning', max_length=255),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='gyroscope_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='driversafetyscan',
            name='spoof_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
